"""empty message

Revision ID: 696da674e8d5
Revises: 89f7831bf2a5
Create Date: 2021-04-15 22:00:42.815014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696da674e8d5'
down_revision = '89f7831bf2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('origin_type', sa.String(length=50), nullable=True),
    sa.Column('connection_weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    # ### end Alembic commands ###
